name: todo_list_provider
description: "A new Flutter project."
version: 0.2.0

publish_to: "none"

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  return_success_or_error: ^0.17.0
  provider: ^6.1.1
  sqflite: ^2.3.2
  path: ^1.8.3
  synchronized: ^3.1.0+1
  google_fonts: ^6.1.0

  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
