name: todo_list_provider
description: "A new Flutter project."
version: 0.2.0

publish_to: "none"

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  return_success_or_error: ^0.18.0
  flutter_getit: ^2.0.0
  get_it: ^7.7.0
  provider: ^6.1.1
  sqflite: ^2.3.2
  path: ^1.8.3
  synchronized: ^3.1.0+1
  google_fonts: ^6.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_remote_config: ^5.1.3
  google_sign_in: ^6.2.1
  firebase_storage: ^12.3.4
  flutter_signin_button: ^2.0.0
  cupertino_icons: ^1.0.2
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.2
  validatorless: ^1.2.3
  flutter_overlay_loader: ^2.0.0
  image_picker: ^1.1.2
  logger: ^2.2.0
  date_picker_timeline: ^1.2.6
  intl: ^0.19.0
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: IconsPadrao
      fonts:
        - asset: assets/fonts/IconsPadrao.ttf

