name: client_android_cuidapet
description: "A new Flutter project."
publish_to: 'none' 
version: 0.0.1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #Dependencias internas
  dependencies:
    path: ../../modules/dependencies
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.2
  build_runner: ^2.4.13
flutter:
  uses-material-design: true
